package eu.jangos.auth.model;
// Generated 06-mai-2016 20:54:54 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bannedaccount generated by hbm2java
 */
@Entity
@Table(name="bannedaccount"
    ,catalog="jangosauth"
)
public class Bannedaccount  implements java.io.Serializable {


     private Integer id;
     private Account accountByFkBannedby;
     private Account accountByFkBannedaccount;
     private Date bandate;
     private Date unban;
     private String reason;
     private boolean active;

    public Bannedaccount() {
    }

	
    public Bannedaccount(Account accountByFkBannedby, Account accountByFkBannedaccount, Date bandate, String reason, boolean active) {
        this.accountByFkBannedby = accountByFkBannedby;
        this.accountByFkBannedaccount = accountByFkBannedaccount;
        this.bandate = bandate;
        this.reason = reason;
        this.active = active;
    }
    public Bannedaccount(Account accountByFkBannedby, Account accountByFkBannedaccount, Date bandate, Date unban, String reason, boolean active) {
       this.accountByFkBannedby = accountByFkBannedby;
       this.accountByFkBannedaccount = accountByFkBannedaccount;
       this.bandate = bandate;
       this.unban = unban;
       this.reason = reason;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_bannedby", nullable=false)
    public Account getAccountByFkBannedby() {
        return this.accountByFkBannedby;
    }
    
    public void setAccountByFkBannedby(Account accountByFkBannedby) {
        this.accountByFkBannedby = accountByFkBannedby;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_bannedaccount", nullable=false)
    public Account getAccountByFkBannedaccount() {
        return this.accountByFkBannedaccount;
    }
    
    public void setAccountByFkBannedaccount(Account accountByFkBannedaccount) {
        this.accountByFkBannedaccount = accountByFkBannedaccount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bandate", nullable=false, length=19)
    public Date getBandate() {
        return this.bandate;
    }
    
    public void setBandate(Date bandate) {
        this.bandate = bandate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="unban", length=19)
    public Date getUnban() {
        return this.unban;
    }
    
    public void setUnban(Date unban) {
        this.unban = unban;
    }

    
    @Column(name="reason", nullable=false)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


