package eu.jangos.auth.model;
// Generated 01-févr.-2016 22:32:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Locale generated by hbm2java
 */
public class Locale  implements java.io.Serializable {


     private int id;
     private String locale;
     private String localeString;
     private Set accounts = new HashSet(0);

    public Locale() {
    }

	
    public Locale(int id, String locale, String localeString) {
        this.id = id;
        this.locale = locale;
        this.localeString = localeString;
    }
    public Locale(int id, String locale, String localeString, Set accounts) {
       this.id = id;
       this.locale = locale;
       this.localeString = localeString;
       this.accounts = accounts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLocale() {
        return this.locale;
    }
    
    public void setLocale(String locale) {
        this.locale = locale;
    }
    public String getLocaleString() {
        return this.localeString;
    }
    
    public void setLocaleString(String localeString) {
        this.localeString = localeString;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


