package eu.jangos.auth.model;
// Generated 01-f�vr.-2016 22:32:30 by Hibernate Tools 4.3.1



/**
 * RealmAccountId generated by hbm2java
 */
public class RealmAccountId  implements java.io.Serializable {


     private int fkAccount;
     private int fkRealm;

    public RealmAccountId() {
    }

    public RealmAccountId(int fkAccount, int fkRealm) {
       this.fkAccount = fkAccount;
       this.fkRealm = fkRealm;
    }
   
    public int getFkAccount() {
        return this.fkAccount;
    }
    
    public void setFkAccount(int fkAccount) {
        this.fkAccount = fkAccount;
    }
    public int getFkRealm() {
        return this.fkRealm;
    }
    
    public void setFkRealm(int fkRealm) {
        this.fkRealm = fkRealm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RealmAccountId) ) return false;
		 RealmAccountId castOther = ( RealmAccountId ) other; 
         
		 return (this.getFkAccount()==castOther.getFkAccount())
 && (this.getFkRealm()==castOther.getFkRealm());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkAccount();
         result = 37 * result + this.getFkRealm();
         return result;
   }   


}


